# Generated by Django 4.2.1 on 2023-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_details',
            name='person1',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='person2',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='person3',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='person4',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
