# Generated by Django 4.2.1 on 2023-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_proj_details_person1_proj_details_person2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_details',
            name='roll1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='roll2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='roll3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='roll4',
            field=models.CharField(default='', max_length=20),
        ),
    ]
