# Generated by Django 4.2.1 on 2023-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_proj_details_roll1_alter_proj_details_roll2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='proj_details',
            old_name='Details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='proj_details',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='Proposer',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='person1',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='person2',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='person3',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='person4',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='roll1',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='roll2',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='roll3',
        ),
        migrations.RemoveField(
            model_name='proj_details',
            name='roll4',
        ),
        migrations.AddField(
            model_name='proj_details',
            name='people',
            field=models.ManyToManyField(related_name='people_involved', to='Project.person'),
        ),
        migrations.AddField(
            model_name='proj_details',
            name='proposer',
            field=models.ManyToManyField(related_name='proposer', to='Project.person'),
        ),
    ]
