# Generated by Django 4.2.1 on 2023-05-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_remove_proj_details_proposer_proj_details_proposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj_details',
            name='proposer',
            field=models.ForeignKey(default='some', on_delete=django.db.models.deletion.CASCADE, related_name='proposer', to='Project.person'),
        ),
    ]
