# Generated by Django 4.2.1 on 2023-05-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_alter_proj_details_proposer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proj_details',
            name='people',
        ),
    ]
