# Generated by Django 4.2.1 on 2023-05-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_remove_proj_details_proposer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
