# Generated by Django 4.2.1 on 2023-05-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='proj_details',
            name='proposer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proposer', to='Project.person'),
        ),
    ]
