# Generated by Django 4.2.1 on 2023-05-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_person_proj_details_proposer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_details',
            name='people',
            field=models.ManyToManyField(related_name='people_involved', to='Project.person'),
        ),
    ]
