# Generated by Django 4.2.1 on 2023-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_alter_proj_details_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roll',
            field=models.IntegerField(max_length=10),
        ),
    ]
