# Generated by Django 4.1.7 on 2023-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_alter_person_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
